// 语言配置文件
const translations = {
    'en': {
        // 导航
        'nav-features': 'Features',
        'nav-demo': 'Demo',
        'nav-contact': 'Contact',
        
        // Hero区域
        'hero-title': 'Welcome to Sora2',
        'hero-subtitle': 'Revolutionary AI Video Generation Platform',
        'hero-description': 'Based on cutting-edge AI technology, Sora2 enables you to easily create high-quality video content. From simple text descriptions to vivid video scenes, everything is at your fingertips.',
        'cta-prompts': 'View Prompts',
        'cta-start': 'Get Started',
        
        // 功能特性
        'features-title': 'Core Features',
        'feature1-title': 'Smart Video Generation',
        'feature1-desc': 'Generate high-quality video content automatically through simple text descriptions',
        'feature2-title': 'Fast Processing',
        'feature2-desc': 'Optimized algorithms ensure rapid generation, saving your valuable time',
        'feature3-title': 'Diverse Styles',
        'feature3-desc': 'Support multiple video styles to meet different scenario requirements',
        
        // 提示词推荐区域
        'prompts-title': 'Prompt Recommendations',
        'prompts-subtitle': 'Discover inspiring prompts to create amazing videos',
        
        // 联系区域
        'contact-title': 'Start Using Now',
        'contact-subtitle': 'Join thousands of creative professionals and experience the future of AI video generation',
        'contact-input-placeholder': 'Please enter your email address',
        'contact-submit-btn': 'Get Access',
        'contact-success-title': 'Thank you for registering!',
        'contact-success-message': 'We have sent access information to',
        
        // 页脚
        'footer-text': '© 2025 Sora2. All rights reserved.',
        
        // 语言切换
        'language-switch': '中文',
        'current-language': 'English',
        
        // 导航 - 新增页面
        'nav-features': 'Features',
        'nav-pricing': 'Pricing',
        'nav-tutorials': 'Tutorials',
        'nav-cases': 'Use Cases',
        'nav-about': 'About',
        'nav-blog': 'Blog',
        
        // 页面标题
        'page-features': 'Features - Sora2',
        'page-pricing': 'Pricing - Sora2',
        'page-tutorials': 'Tutorials - Sora2',
        'page-cases': 'Use Cases - Sora2',
        'page-about': 'About - Sora2',
        'page-blog': 'Blog - Sora2',
        
        // SEO内容
        'meta-description': 'Sora2 - AI video generation platform that creates professional videos from text descriptions. Text-to-video AI technology for creative content.',
        'meta-keywords': 'AI Video Generation,Text-to-Video,Sora2,AI Video Creator,Video AI',
        'og-title': 'Sora2 - AI Video Generation Technology',
        'og-description': 'Advanced AI video generation platform that creates professional video content through simple text descriptions.',
        'twitter-title': 'Sora2 - AI Video Generation Technology',
        'twitter-description': 'Advanced AI video generation platform that creates professional video content through simple text descriptions.',
        
        // 各页面SEO描述
        'meta-features-description': 'Explore Sora2 features: AI video generation, text-to-video conversion, multiple styles, fast processing, and advanced editing tools.',
        'meta-pricing-description': 'Sora2 pricing plans: Free trial, Pro plan, and Enterprise solutions for AI video generation needs.',
        'meta-tutorials-description': 'Learn how to use Sora2 with step-by-step tutorials for AI video generation and text-to-video creation.',
        'meta-cases-description': 'See real-world use cases of Sora2 AI video generation technology across different industries and applications.',
        'meta-about-description': 'Learn about Sora2 company, mission, and the team behind the AI video generation technology.',
        'meta-blog-description': 'Sora2 blog: Latest news, updates, and insights about AI video generation technology and industry trends.'
    },
    'zh': {
        // 导航
        'nav-features': '功能特性',
        'nav-demo': '演示',
        'nav-contact': '联系我们',
        
        // Hero区域
        'hero-title': '欢迎来到 Sora2',
        'hero-subtitle': '革命性的AI视频生成平台',
        'hero-description': '基于最先进的AI技术，Sora2让您能够轻松创建高质量的视频内容。从简单的文本描述到生动的视频画面，一切尽在掌握。',
        'cta-prompts': '查看提示词',
        'cta-start': '开始使用',
        
        // 功能特性
        'features-title': '核心功能',
        'feature1-title': '智能视频生成',
        'feature1-desc': '通过简单的文本描述，自动生成高质量的视频内容',
        'feature2-title': '快速处理',
        'feature2-desc': '优化的算法确保快速生成，节省您宝贵的时间',
        'feature3-title': '多样化风格',
        'feature3-desc': '支持多种视频风格，满足不同场景需求',
        
        // 提示词推荐区域
        'prompts-title': '提示词推荐',
        'prompts-subtitle': '发现精彩的提示词，创作惊艳的视频',
        
        // 联系区域
        'contact-title': '立即开始使用',
        'contact-subtitle': '加入数千名创意工作者，体验AI视频生成的未来',
        'contact-input-placeholder': '请输入您的邮箱地址',
        'contact-submit-btn': '获取访问权限',
        'contact-success-title': '感谢您的注册！',
        'contact-success-message': '我们已向',
        'contact-success-message2': '发送了访问权限信息',
        
        // 页脚
        'footer-text': '© 2025 Sora2. 保留所有权利。',
        
        // 语言切换
        'language-switch': 'English',
        'current-language': '简体中文',
        
        // 导航 - 新增页面
        'nav-features': '功能特性',
        'nav-pricing': '定价方案',
        'nav-tutorials': '使用教程',
        'nav-cases': '案例展示',
        'nav-about': '关于我们',
        'nav-blog': '博客',
        
        // 页面标题
        'page-features': '功能特性 - Sora2',
        'page-pricing': '定价方案 - Sora2',
        'page-tutorials': '使用教程 - Sora2',
        'page-cases': '案例展示 - Sora2',
        'page-about': '关于我们 - Sora2',
        'page-blog': '博客 - Sora2',
        
        // SEO内容
        'meta-description': 'Sora2 - 基于AI技术的高质量视频生成平台，通过简单文本描述创建专业视频内容。AI视频生成、文本转视频、智能创作工具。',
        'meta-keywords': 'AI视频生成,文本转视频,Sora2,人工智能视频,AI创作工具,视频生成平台',
        'og-title': 'Sora2 - AI视频生成平台',
        'og-description': '基于AI技术的高质量视频生成平台，通过简单文本描述创建专业视频内容。',
        'twitter-title': 'Sora2 - AI视频生成平台',
        'twitter-description': '基于AI技术的高质量视频生成平台，通过简单文本描述创建专业视频内容。',
        
        // 各页面SEO描述
        'meta-features-description': '探索Sora2功能特性：AI视频生成、文本转视频转换、多种风格、快速处理、高级编辑工具。',
        'meta-pricing-description': 'Sora2定价方案：免费试用、专业版计划、企业解决方案，满足不同AI视频生成需求。',
        'meta-tutorials-description': '学习如何使用Sora2，提供AI视频生成和文本转视频创建的详细使用教程。',
        'meta-cases-description': '查看Sora2 AI视频生成技术在不同行业和应用场景中的真实案例展示。',
        'meta-about-description': '了解Sora2公司、使命以及AI视频生成技术背后的团队。',
        'meta-blog-description': 'Sora2博客：关于AI视频生成技术的最新新闻、更新和行业趋势见解。',
        
        // About页面翻译
        'about-page-title': '关于Sora2',
        'about-page-subtitle': '通过先进的AI技术让视频创作民主化',
        'about-mission-title': '我们的使命',
        'about-mission-text': 'Sora2成立时有一个简单而强大的愿景：让专业视频创作对每个人都触手可及。我们相信引人注目的视频内容不应该受到预算、技术专长或制作资源的限制。',
        'about-mission-text2': '通过利用尖端的人工智能技术，我们正在打破障碍，赋能企业、创作者和个人通过高质量的视频内容讲述他们的故事。',
        'about-team-title': '我们的团队',
        'about-team-text': 'Sora2汇聚了AI研究、视频制作和用户体验设计领域的专家。我们多元化的团队因对创新的共同热情和为用户提供卓越价值的承诺而团结在一起。',
        'about-stat1': 'AI研究员',
        'about-stat2': '年经验',
        'about-stat3': '生成视频',
        'about-tech-title': '我们的技术',
        'about-tech-text': 'Sora2利用在数百万视频样本上训练的最先进机器学习模型。我们的专有算法理解上下文、情感和视觉叙事，生成能与观众产生共鸣的视频。',
        'about-tech1-title': '高级自然语言处理',
        'about-tech1-desc': '理解意图和上下文的自然语言处理技术',
        'about-tech2-title': '计算机视觉',
        'about-tech2-desc': '用于逼真视频生成的复杂视觉理解技术',
        'about-tech3-title': '实时处理',
        'about-tech3-desc': '优化算法实现快速、高效的视频创建',
        'about-values-title': '我们的价值观',
        'about-value1-title': '创新',
        'about-value1-desc': '不断推动AI视频生成可能性的边界',
        'about-value2-title': '可访问性',
        'about-value2-desc': '让所有技能水平的用户都能使用先进技术',
        'about-value3-title': '质量',
        'about-value3-desc': '在视频输出和用户体验方面保持最高标准',
        'about-cta-title': '加入我们的愿景',
        'about-cta-subtitle': '与Sora2一起成为视频创作革命的一部分',
        'about-cta-features': '探索功能',
        'about-cta-demo': '试用演示',
        
        // Features页面翻译
        'features-page-title': '先进的AI视频生成功能',
        'features-page-subtitle': '专业视频内容创作的强大工具',
        'feature-smart-title': '智能文本转视频生成',
        'feature-smart-desc': '通过我们先进的AI算法将简单的文本描述转换为高质量的视频内容。我们的系统理解上下文、情感和视觉需求，创造引人注目的视频。',
        'feature-smart-item1': '自然语言处理确保准确解释',
        'feature-smart-item2': '上下文感知的视频生成',
        'feature-smart-item3': '情感和语调识别',
        'feature-smart-item4': '多场景视频创建',
        'feature-speed-title': '闪电般快速处理',
        'feature-speed-desc': '优化的算法确保快速视频生成而不影响质量。在几分钟内处理复杂的视频请求，而不是几小时。',
        'feature-speed-item1': 'GPU加速处理',
        'feature-speed-item2': '批量视频生成',
        'feature-speed-item3': '实时预览功能',
        'feature-speed-item4': '可扩展的基础设施',
        'feature-styles-title': '多样化视频风格',
        'feature-styles-desc': '从多种视频风格中选择，以匹配您的品牌身份和内容需求。从企业演示到创意叙事。',
        'feature-styles-item1': '专业企业风格',
        'feature-styles-item2': '创意动画风格',
        'feature-styles-item3': '社交媒体优化',
        'feature-styles-item4': '自定义风格开发',
        'feature-quality-title': '专业品质输出',
        'feature-quality-desc': '生成具有高分辨率、流畅动画和专业编辑的工作室品质视频。适用于所有平台和用途。',
        'feature-quality-item1': '4K分辨率支持',
        'feature-quality-item2': '专业音频集成',
        'feature-quality-item3': '多格式导出选项',
        'feature-quality-item4': '平台优化输出',
        'features-cta-title': '准备体验先进的AI视频生成了吗？',
        'features-cta-subtitle': '今天就开始使用Sora2创建专业视频',
        'features-cta-pricing': '查看定价',
        'features-cta-demo': '试用演示',
        
        // Pricing页面翻译
        'pricing-page-title': '简单、透明的定价',
        'pricing-page-subtitle': '选择最适合您视频创作需求的计划',
        'pricing-per-month': '/月',
        'pricing-popular': '最受欢迎',
        'pricing-basic-title': '入门版',
        'pricing-basic-desc': '适合个人和小型项目',
        'pricing-basic-feature1': '每月50次视频生成',
        'pricing-basic-feature2': '1080p分辨率',
        'pricing-basic-feature3': '3种视频风格',
        'pricing-basic-feature4': '基础支持',
        'pricing-basic-feature5': '5GB存储空间',
        'pricing-pro-title': '专业版',
        'pricing-pro-desc': '适合内容创作者和小团队',
        'pricing-pro-feature1': '每月200次视频生成',
        'pricing-pro-feature2': '4K分辨率',
        'pricing-pro-feature3': '所有视频风格',
        'pricing-pro-feature4': '优先支持',
        'pricing-pro-feature5': '50GB存储空间',
        'pricing-pro-feature6': '批量处理',
        'pricing-enterprise-title': '企业版',
        'pricing-enterprise-desc': '适合大型组织和代理机构',
        'pricing-enterprise-feature1': '无限视频生成',
        'pricing-enterprise-feature2': '4K分辨率 + HDR',
        'pricing-enterprise-feature3': '自定义视频风格',
        'pricing-enterprise-feature4': '专属支持',
        'pricing-enterprise-feature5': '500GB存储空间',
        'pricing-enterprise-feature6': 'API访问',
        'pricing-enterprise-feature7': '团队协作',
        'pricing-get-started': '开始使用',
        'pricing-contact-sales': '联系销售',
        'pricing-faq-title': '常见问题',
        'pricing-faq1-question': '我可以稍后更改计划吗？',
        'pricing-faq1-answer': '是的，您可以随时升级或降级您的计划。更改立即生效。',
        'pricing-faq2-question': '有免费试用吗？',
        'pricing-faq2-answer': '我们为所有计划提供14天免费试用。开始时无需信用卡。',
        'pricing-faq3-question': '您接受哪些付款方式？',
        'pricing-faq3-answer': '我们接受所有主要信用卡、PayPal，企业计划还支持银行转账。',
        
        // Cases页面翻译
        'cases-page-title': 'Sora2成功案例',
        'cases-page-subtitle': '看看企业如何通过AI改变他们的视频内容',
        'case1-title': '科技初创公司通过AI视频提升营销效果',
        'case1-industry': '行业：科技与营销',
        'case1-result1': '视频制作速度提升',
        'case1-result2': '内容产出增加',
        'case1-result3': '成本降低',
        'case1-description': '一家成长中的科技初创公司使用Sora2创建产品演示视频和营销内容。他们将制作时间从几周缩短到几天，同时保持专业品质。',
        'case1-quote': '"Sora2改变了我们的内容策略。我们现在可以按需创建高质量视频，保持营销内容的新鲜和吸引力。"',
        'case2-title': '教育平台扩大内容创作规模',
        'case2-industry': '行业：教育与在线学习',
        'case2-result1': '每月创建视频',
        'case2-result2': '学生满意度',
        'case2-result3': '时间节省',
        'case2-description': '一个在线教育平台集成Sora2为复杂主题生成解释视频。他们扩大了内容库规模，同时保持教育质量。',
        'case2-quote': '"快速创建视觉解释的能力彻底改变了我们的教学方法。学生们喜欢这些引人入胜的内容。"',
        'case3-title': '电商品牌增强产品视频',
        'case3-industry': '行业：电子商务与零售',
        'case3-result1': '产品视频增加',
        'case3-result2': '转化率提高',
        'case3-result3': '上市时间缩短',
        'case3-description': '一个主要电商品牌使用Sora2为整个产品目录创建产品演示视频。他们显著提高了客户参与度和销售额。',
        'case3-quote': '"视频内容是我们的瓶颈。有了Sora2，我们可以为每个产品制作专业视频，推动更好的客户决策。"',
        
        // Tutorials页面翻译
        'tutorials-page-title': 'Sora2教程与指南',
        'tutorials-page-subtitle': '学习如何使用我们的AI技术创建精彩视频',
        'tutorial-beginner-title': '入门指南',
        'tutorial-beginner-desc': '学习Sora2基础知识并创建您的第一个AI生成视频',
        'tutorial-beginner1': '创建您的第一个视频',
        'tutorial-beginner2': '理解文本提示',
        'tutorial-beginner3': '基本视频设置',
        'tutorial-intermediate-title': '高级技巧',
        'tutorial-intermediate-desc': '掌握专业视频创作的高级功能',
        'tutorial-intermediate1': '高级提示工程',
        'tutorial-intermediate2': '风格自定义',
        'tutorial-intermediate3': '批量处理',
        'tutorial-expert-title': '专业工作流程',
        'tutorial-expert-desc': '优化您的工作流程以获得最大效率',
        'tutorial-expert1': '团队协作',
        'tutorial-expert2': 'API集成',
        'tutorial-expert3': '质量优化',
        'tutorial-featured-title': '精选教程：创建营销视频',
        'tutorial-step1-title': '第1步：定义您的目标',
        'tutorial-step1-desc': '首先明确定义您想通过视频实现什么。您是在推广产品、解释服务还是讲述故事？',
        'tutorial-step2-title': '第2步：制作您的提示',
        'tutorial-step2-desc': '写一个详细的文本描述，包括您想要传达的场景、角色、动作和情感。',
        'tutorial-step3-title': '第3步：选择视频风格',
        'tutorial-step3-desc': '选择与您的品牌和信息匹配的适当视频风格。考虑企业、创意或社交媒体风格。',
        'tutorial-step4-title': '第4步：生成和完善',
        'tutorial-step4-desc': '生成您的视频并查看结果。如需获得最佳效果，可根据需要调整您的提示。'
    }
};

// 提示词数据
/*
const promptsData = {
    en: [
        "A cinematic shot of a hamster wearing a tiny chef's hat, meticulously preparing a miniature gourmet meal in a rustic kitchen.",
        "An epic fantasy landscape with floating islands, majestic waterfalls, and a dragon soaring through the sky, in the style of a high-fantasy painting.",
        "A futuristic cityscape at night, with flying vehicles, holographic advertisements, and towering skyscrapers, in a cyberpunk aesthetic.",
        "A heartwarming scene of a golden retriever puppy discovering its reflection in a puddle for the first time.",
        "A surreal, dreamlike forest where the trees have glowing leaves and the ground is covered in a soft, pulsating light.",
        "A time-lapse video of a flower blooming, from a tight bud to a full, vibrant blossom, with dramatic lighting.",
        "An action-packed sequence of a secret agent parkouring across rooftops in a bustling Moroccan market.",
        "A serene underwater world filled with colorful coral reefs, exotic fish, and a gentle sea turtle gliding by.",
        "A historical reenactment of a medieval knight's duel, with authentic armor, clashing swords, and a dramatic castle backdrop.",
        "A whimsical animation of a group of friendly monsters throwing a surprise birthday party for a sad, lost cloud.",
        "A close-up shot of a honeybee collecting nectar from a flower, with pollen dusting its fuzzy body, in ultra-high definition.",
        "A dramatic, slow-motion video of a water balloon bursting, with the water splashing in intricate patterns.",
        "A cozy, rain-swept café in Paris, with steam rising from a cup of coffee on a small, round table.",
        "A thrilling first-person view of a rollercoaster ride, capturing the twists, turns, and drops with exhilarating speed.",
        "A magical scene of fireflies illuminating a dark forest, creating a celestial, starry-night effect on the ground.",
        "A stylish, black-and-white film noir scene with a detective in a trench coat standing under a flickering streetlamp in a foggy alley.",
        "A vibrant, bustling street market in India, filled with colorful spices, textiles, and the sounds of a lively crowd.",
        "A breathtaking aerial shot of a massive glacier calving, with a huge chunk of ice breaking off and crashing into the ocean.",
        "A charming stop-motion animation of a family of clay penguins having a picnic on a snowy hill.",
        "A powerful, cinematic shot of a lone wolf howling at the moon on a snowy mountain peak.",
        "A time-lapse of a bustling city intersection, showing the flow of traffic and pedestrians like streams of light.",
        "A beautiful, sun-drenched vineyard in Tuscany, with rows of grapevines stretching into the rolling hills.",
        "A futuristic robot butler serving drinks at a sophisticated cocktail party in a luxurious penthouse.",
        "A close-up of a cat's eye, with the pupil dilating and contracting, showing incredible detail and color.",
        "A dynamic, high-speed chase between two sports cars on a winding coastal highway at sunset.",
        "A peaceful, zen-like garden with a koi pond, a small wooden bridge, and cherry blossom trees in full bloom.",
        "An adventurous scene of a group of friends hiking to the top of a mountain and celebrating at the summit.",
        "A spooky, atmospheric video of a haunted house, with creaking doors, flickering lights, and shadowy figures.",
        "A delightful animation of a piece of popcorn kernel transforming into a fluffy popcorn with a big personality.",
        "A majestic, slow-motion shot of a bald eagle catching a fish from a river, with water droplets flying everywhere."
    ],
    zh: [
        "一只穿着迷你厨师帽的仓鼠，在质朴的厨房里精心准备微型美食的电影镜头。",
        "史诗般的奇幻景观，有漂浮的岛屿、雄伟的瀑布和翱翔在天空中的巨龙，风格如同高度奇幻的绘画。",
        "未来派的夜间城市景观，有飞行汽车、全息广告和高耸的摩天大楼，呈现赛博朋克美学。",
        "一只金毛寻回犬幼犬第一次在水坑里发现自己倒影的温馨场面。",
        "一个超现实、梦幻般的森林，树叶发光，地面覆盖着柔和、脉动的光。",
        "一朵花盛开的延时视频，从紧凑的花蕾到完全绽放的鲜艳花朵，灯光效果引人注目。",
        "一名特工在熙熙攘攘的摩洛哥市场上飞檐走壁的动作场面。",
        "一个宁静的海底世界，充满了五彩斑斓的珊瑚礁、奇异的鱼类和一只温柔滑翔的海龟。",
        "中世纪骑士决斗的历史重现，有真实的盔甲、碰撞的剑和引人注目的城堡背景。",
        "一群友好的怪物为一个悲伤、迷失的云朵举办惊喜生日派对的异想天成的动画。",
        "一只蜜蜂从花中采集花蜜的特写镜头，花粉撒在它毛茸茸的身体上，超高清画质。",
        "一个水气球爆裂的戏剧性慢动作视频，水花飞溅成复杂的图案。",
        "一个舒适、雨中的巴黎咖啡馆，一个小圆桌上的一杯咖啡冒着热气。",
        "过山车的第一人称惊险视角，以令人振奋的速度捕捉曲折、转弯和下降。",
        "萤火虫照亮黑暗森林的神奇景象，在地面上创造出如星夜般的效果。",
        "一个时尚的黑白电影黑色场景，一个穿着风衣的侦探站在有雾的小巷里闪烁的路灯下。",
        "一个充满活力的、熙熙攘攘的印度街头市场，充满了五颜六色的香料、纺织品和热闹人群的声音。",
        "一个巨大的冰川崩解的惊人航拍镜头，一大块冰脱落并坠入海洋。",
        "一个由黏土企鹅组成的家庭在雪山上野餐的迷人定格动画。",
        "一只孤狼在雪山顶上对月嚎叫的强有力的电影镜头。",
        "一个繁华城市十字路口的延时摄影，展示了像光流一样的车流和人流。",
        "一个美丽的、阳光普照的托斯卡纳葡萄园，一排排的葡萄藤延伸到连绵起伏的丘陵中。",
        "一个未来派的机器人管家在豪华顶层公寓的精致鸡尾酒会上提供饮料。",
        "一只猫眼的特写，瞳孔放大和收缩，显示出令人难以置信的细节和颜色。",
        "两辆跑车在日落时分蜿蜒的沿海公路上进行动态高速追逐。",
        "一个宁静的、禅宗般的花园，有锦鲤池、一座小木桥和盛开的樱花树。",
        "一群朋友徒步到山顶并在山顶庆祝的冒险场面。",
        "一个鬼屋的恐怖、有气氛的视频，有吱吱作响的门、闪烁的灯光和阴影中的人影。",
        "一个爆米花粒变成一个有个性的蓬松爆米花的愉快动画。",
        "一只秃鹰从河里抓鱼的雄伟慢动作镜头，水滴四处飞溅。"
    ]
};
*/