// 语言配置文件
const translations = {
    'en': {
        // 导航
        'nav-features': 'Features',
        'nav-demo': 'Demo',
        'nav-contact': 'Contact',
        
        // Hero区域
        'hero-title': 'Welcome to Sora2',
        'hero-subtitle': 'Revolutionary AI Video Generation Platform',
        'hero-description': 'Based on cutting-edge AI technology, Sora2 enables you to easily create high-quality video content. From simple text descriptions to vivid video scenes, everything is at your fingertips.',
        'cta-prompts': 'View Prompts',
        'cta-start': 'Get Started',
        
        // 功能特性
        'features-title': 'Core Features',
        'feature1-title': 'Smart Video Generation',
        'feature1-desc': 'Generate high-quality video content automatically through simple text descriptions',
        'feature2-title': 'Fast Processing',
        'feature2-desc': 'Optimized algorithms ensure rapid generation, saving your valuable time',
        'feature3-title': 'Diverse Styles',
        'feature3-desc': 'Support multiple video styles to meet different scenario requirements',
        
        // 提示词推荐区域
        'prompts-title': 'Prompt Recommendations',
        'prompts-subtitle': 'Discover inspiring prompts to create amazing videos',
        
        // 联系区域
        'contact-title': 'Start Using Now',
        'contact-subtitle': 'Join thousands of creative professionals and experience the future of AI video generation',
        'contact-input-placeholder': 'Please enter your email address',
        'contact-submit-btn': 'Get Access',
        'contact-success-title': 'Thank you for registering!',
        'contact-success-message': 'We have sent access information to',
        
        // 页脚
        'footer-text': '© 2025 Sora2. All rights reserved.',
        
        // 语言切换
        'language-switch': '中文',
        'current-language': 'English',
        
        // 导航 - 新增页面
        'nav-features': 'Features',
        'nav-pricing': 'Pricing',
        'nav-tutorials': 'Tutorials',
        'nav-cases': 'Use Cases',
        'nav-about': 'About',
        'nav-blog': 'Blog',
        
        // 页面标题
        'page-features': 'Features - Sora2',
        'page-pricing': 'Pricing - Sora2',
        'page-tutorials': 'Tutorials - Sora2',
        'page-cases': 'Use Cases - Sora2',
        'page-about': 'About - Sora2',
        'page-blog': 'Blog - Sora2',
        
        // SEO内容
        'meta-description': 'Sora2 - AI video generation platform that creates professional videos from text descriptions. Text-to-video AI technology for creative content.',
        'meta-keywords': 'AI Video Generation,Text-to-Video,Sora2,AI Video Creator,Video AI',
        'og-title': 'Sora2 - AI Video Generation Technology',
        'og-description': 'Advanced AI video generation platform that creates professional video content through simple text descriptions.',
        'twitter-title': 'Sora2 - AI Video Generation Technology',
        'twitter-description': 'Advanced AI video generation platform that creates professional video content through simple text descriptions.',
        
        // 各页面SEO描述
        'meta-features-description': 'Explore Sora2 features: AI video generation, text-to-video conversion, multiple styles, fast processing, and advanced editing tools.',
        'meta-pricing-description': 'Sora2 pricing plans: Free trial, Pro plan, and Enterprise solutions for AI video generation needs.',
        'meta-tutorials-description': 'Learn how to use Sora2 with step-by-step tutorials for AI video generation and text-to-video creation.',
        'meta-cases-description': 'See real-world use cases of Sora2 AI video generation technology across different industries and applications.',
        'meta-about-description': 'Learn about Sora2 company, mission, and the team behind the AI video generation technology.',
        'meta-blog-description': 'Sora2 blog: Latest news, updates, and insights about AI video generation technology and industry trends.'
    },
    'zh': {
        // 导航
        'nav-features': '功能特性',
        'nav-demo': '演示',
        'nav-contact': '联系我们',
        
        // Hero区域
        'hero-title': '欢迎来到 Sora2',
        'hero-subtitle': '革命性的AI视频生成平台',
        'hero-description': '基于最先进的AI技术，Sora2让您能够轻松创建高质量的视频内容。从简单的文本描述到生动的视频画面，一切尽在掌握。',
        'cta-prompts': '查看提示词',
        'cta-start': '开始使用',
        
        // 功能特性
        'features-title': '核心功能',
        'feature1-title': '智能视频生成',
        'feature1-desc': '通过简单的文本描述，自动生成高质量的视频内容',
        'feature2-title': '快速处理',
        'feature2-desc': '优化的算法确保快速生成，节省您宝贵的时间',
        'feature3-title': '多样化风格',
        'feature3-desc': '支持多种视频风格，满足不同场景需求',
        
        // 提示词推荐区域
        'prompts-title': '提示词推荐',
        'prompts-subtitle': '发现精彩的提示词，创作惊艳的视频',
        
        // 联系区域
        'contact-title': '立即开始使用',
        'contact-subtitle': '加入数千名创意工作者，体验AI视频生成的未来',
        'contact-input-placeholder': '请输入您的邮箱地址',
        'contact-submit-btn': '获取访问权限',
        'contact-success-title': '感谢您的注册！',
        'contact-success-message': '我们已向',
        'contact-success-message2': '发送了访问权限信息',
        
        // 页脚
        'footer-text': '© 2025 Sora2. 保留所有权利。',
        
        // 语言切换
        'language-switch': 'English',
        'current-language': '简体中文',
        
        // 导航 - 新增页面
        'nav-features': '功能特性',
        'nav-pricing': '定价方案',
        'nav-tutorials': '使用教程',
        'nav-cases': '案例展示',
        'nav-about': '关于我们',
        'nav-blog': '博客',
        
        // 页面标题
        'page-features': '功能特性 - Sora2',
        'page-pricing': '定价方案 - Sora2',
        'page-tutorials': '使用教程 - Sora2',
        'page-cases': '案例展示 - Sora2',
        'page-about': '关于我们 - Sora2',
        'page-blog': '博客 - Sora2',
        
        // SEO内容
        'meta-description': 'Sora2 - 基于AI技术的高质量视频生成平台，通过简单文本描述创建专业视频内容。AI视频生成、文本转视频、智能创作工具。',
        'meta-keywords': 'AI视频生成,文本转视频,Sora2,人工智能视频,AI创作工具,视频生成平台',
        'og-title': 'Sora2 - AI视频生成平台',
        'og-description': '基于AI技术的高质量视频生成平台，通过简单文本描述创建专业视频内容。',
        'twitter-title': 'Sora2 - AI视频生成平台',
        'twitter-description': '基于AI技术的高质量视频生成平台，通过简单文本描述创建专业视频内容。',
        
        // 各页面SEO描述
        'meta-features-description': '探索Sora2功能特性：AI视频生成、文本转视频转换、多种风格、快速处理、高级编辑工具。',
        'meta-pricing-description': 'Sora2定价方案：免费试用、专业版计划、企业解决方案，满足不同AI视频生成需求。',
        'meta-tutorials-description': '学习如何使用Sora2，提供AI视频生成和文本转视频创建的详细使用教程。',
        'meta-cases-description': '查看Sora2 AI视频生成技术在不同行业和应用场景中的真实案例展示。',
        'meta-about-description': '了解Sora2公司、使命以及AI视频生成技术背后的团队。',
        'meta-blog-description': 'Sora2博客：关于AI视频生成技术的最新新闻、更新和行业趋势见解。',
        
        // About页面翻译
        'about-page-title': '关于Sora2',
        'about-page-subtitle': '通过先进的AI技术让视频创作民主化',
        'about-mission-title': '我们的使命',
        'about-mission-text': 'Sora2成立时有一个简单而强大的愿景：让专业视频创作对每个人都触手可及。我们相信引人注目的视频内容不应该受到预算、技术专长或制作资源的限制。',
        'about-mission-text2': '通过利用尖端的人工智能技术，我们正在打破障碍，赋能企业、创作者和个人通过高质量的视频内容讲述他们的故事。',
        'about-team-title': '我们的团队',
        'about-team-text': 'Sora2汇聚了AI研究、视频制作和用户体验设计领域的专家。我们多元化的团队因对创新的共同热情和为用户提供卓越价值的承诺而团结在一起。',
        'about-stat1': 'AI研究员',
        'about-stat2': '年经验',
        'about-stat3': '生成视频',
        'about-tech-title': '我们的技术',
        'about-tech-text': 'Sora2利用在数百万视频样本上训练的最先进机器学习模型。我们的专有算法理解上下文、情感和视觉叙事，生成能与观众产生共鸣的视频。',
        'about-tech1-title': '高级自然语言处理',
        'about-tech1-desc': '理解意图和上下文的自然语言处理技术',
        'about-tech2-title': '计算机视觉',
        'about-tech2-desc': '用于逼真视频生成的复杂视觉理解技术',
        'about-tech3-title': '实时处理',
        'about-tech3-desc': '优化算法实现快速、高效的视频创建',
        'about-values-title': '我们的价值观',
        'about-value1-title': '创新',
        'about-value1-desc': '不断推动AI视频生成可能性的边界',
        'about-value2-title': '可访问性',
        'about-value2-desc': '让所有技能水平的用户都能使用先进技术',
        'about-value3-title': '质量',
        'about-value3-desc': '在视频输出和用户体验方面保持最高标准',
        'about-cta-title': '加入我们的愿景',
        'about-cta-subtitle': '与Sora2一起成为视频创作革命的一部分',
        'about-cta-features': '探索功能',
        'about-cta-demo': '试用演示',
        
        // Features页面翻译
        'features-page-title': '先进的AI视频生成功能',
        'features-page-subtitle': '专业视频内容创作的强大工具',
        'feature-smart-title': '智能文本转视频生成',
        'feature-smart-desc': '通过我们先进的AI算法将简单的文本描述转换为高质量的视频内容。我们的系统理解上下文、情感和视觉需求，创造引人注目的视频。',
        'feature-smart-item1': '自然语言处理确保准确解释',
        'feature-smart-item2': '上下文感知的视频生成',
        'feature-smart-item3': '情感和语调识别',
        'feature-smart-item4': '多场景视频创建',
        'feature-speed-title': '闪电般快速处理',
        'feature-speed-desc': '优化的算法确保快速视频生成而不影响质量。在几分钟内处理复杂的视频请求，而不是几小时。',
        'feature-speed-item1': 'GPU加速处理',
        'feature-speed-item2': '批量视频生成',
        'feature-speed-item3': '实时预览功能',
        'feature-speed-item4': '可扩展的基础设施',
        'feature-styles-title': '多样化视频风格',
        'feature-styles-desc': '从多种视频风格中选择，以匹配您的品牌身份和内容需求。从企业演示到创意叙事。',
        'feature-styles-item1': '专业企业风格',
        'feature-styles-item2': '创意动画风格',
        'feature-styles-item3': '社交媒体优化',
        'feature-styles-item4': '自定义风格开发',
        'feature-quality-title': '专业品质输出',
        'feature-quality-desc': '生成具有高分辨率、流畅动画和专业编辑的工作室品质视频。适用于所有平台和用途。',
        'feature-quality-item1': '4K分辨率支持',
        'feature-quality-item2': '专业音频集成',
        'feature-quality-item3': '多格式导出选项',
        'feature-quality-item4': '平台优化输出',
        'features-cta-title': '准备体验先进的AI视频生成了吗？',
        'features-cta-subtitle': '今天就开始使用Sora2创建专业视频',
        'features-cta-pricing': '查看定价',
        'features-cta-demo': '试用演示',
        
        // Pricing页面翻译
        'pricing-page-title': '简单、透明的定价',
        'pricing-page-subtitle': '选择最适合您视频创作需求的计划',
        'pricing-per-month': '/月',
        'pricing-popular': '最受欢迎',
        'pricing-basic-title': '入门版',
        'pricing-basic-desc': '适合个人和小型项目',
        'pricing-basic-feature1': '每月50次视频生成',
        'pricing-basic-feature2': '1080p分辨率',
        'pricing-basic-feature3': '3种视频风格',
        'pricing-basic-feature4': '基础支持',
        'pricing-basic-feature5': '5GB存储空间',
        'pricing-pro-title': '专业版',
        'pricing-pro-desc': '适合内容创作者和小团队',
        'pricing-pro-feature1': '每月200次视频生成',
        'pricing-pro-feature2': '4K分辨率',
        'pricing-pro-feature3': '所有视频风格',
        'pricing-pro-feature4': '优先支持',
        'pricing-pro-feature5': '50GB存储空间',
        'pricing-pro-feature6': '批量处理',
        'pricing-enterprise-title': '企业版',
        'pricing-enterprise-desc': '适合大型组织和代理机构',
        'pricing-enterprise-feature1': '无限视频生成',
        'pricing-enterprise-feature2': '4K分辨率 + HDR',
        'pricing-enterprise-feature3': '自定义视频风格',
        'pricing-enterprise-feature4': '专属支持',
        'pricing-enterprise-feature5': '500GB存储空间',
        'pricing-enterprise-feature6': 'API访问',
        'pricing-enterprise-feature7': '团队协作',
        'pricing-get-started': '开始使用',
        'pricing-contact-sales': '联系销售',
        'pricing-faq-title': '常见问题',
        'pricing-faq1-question': '我可以稍后更改计划吗？',
        'pricing-faq1-answer': '是的，您可以随时升级或降级您的计划。更改立即生效。',
        'pricing-faq2-question': '有免费试用吗？',
        'pricing-faq2-answer': '我们为所有计划提供14天免费试用。开始时无需信用卡。',
        'pricing-faq3-question': '您接受哪些付款方式？',
        'pricing-faq3-answer': '我们接受所有主要信用卡、PayPal，企业计划还支持银行转账。',
        
        // Cases页面翻译
        'cases-page-title': 'Sora2成功案例',
        'cases-page-subtitle': '看看企业如何通过AI改变他们的视频内容',
        'case1-title': '科技初创公司通过AI视频提升营销效果',
        'case1-industry': '行业：科技与营销',
        'case1-result1': '视频制作速度提升',
        'case1-result2': '内容产出增加',
        'case1-result3': '成本降低',
        'case1-description': '一家成长中的科技初创公司使用Sora2创建产品演示视频和营销内容。他们将制作时间从几周缩短到几天，同时保持专业品质。',
        'case1-quote': '"Sora2改变了我们的内容策略。我们现在可以按需创建高质量视频，保持营销内容的新鲜和吸引力。"',
        'case2-title': '教育平台扩大内容创作规模',
        'case2-industry': '行业：教育与在线学习',
        'case2-result1': '每月创建视频',
        'case2-result2': '学生满意度',
        'case2-result3': '时间节省',
        'case2-description': '一个在线教育平台集成Sora2为复杂主题生成解释视频。他们扩大了内容库规模，同时保持教育质量。',
        'case2-quote': '"快速创建视觉解释的能力彻底改变了我们的教学方法。学生们喜欢这些引人入胜的内容。"',
        'case3-title': '电商品牌增强产品视频',
        'case3-industry': '行业：电子商务与零售',
        'case3-result1': '产品视频增加',
        'case3-result2': '转化率提高',
        'case3-result3': '上市时间缩短',
        'case3-description': '一个主要电商品牌使用Sora2为整个产品目录创建产品演示视频。他们显著提高了客户参与度和销售额。',
        'case3-quote': '"视频内容是我们的瓶颈。有了Sora2，我们可以为每个产品制作专业视频，推动更好的客户决策。"',
        
        // Tutorials页面翻译
        'tutorials-page-title': 'Sora2教程与指南',
        'tutorials-page-subtitle': '学习如何使用我们的AI技术创建精彩视频',
        'tutorial-beginner-title': '入门指南',
        'tutorial-beginner-desc': '学习Sora2基础知识并创建您的第一个AI生成视频',
        'tutorial-beginner1': '创建您的第一个视频',
        'tutorial-beginner2': '理解文本提示',
        'tutorial-beginner3': '基本视频设置',
        'tutorial-intermediate-title': '高级技巧',
        'tutorial-intermediate-desc': '掌握专业视频创作的高级功能',
        'tutorial-intermediate1': '高级提示工程',
        'tutorial-intermediate2': '风格自定义',
        'tutorial-intermediate3': '批量处理',
        'tutorial-expert-title': '专业工作流程',
        'tutorial-expert-desc': '优化您的工作流程以获得最大效率',
        'tutorial-expert1': '团队协作',
        'tutorial-expert2': 'API集成',
        'tutorial-expert3': '质量优化',
        'tutorial-featured-title': '精选教程：创建营销视频',
        'tutorial-step1-title': '第1步：定义您的目标',
        'tutorial-step1-desc': '首先明确定义您想通过视频实现什么。您是在推广产品、解释服务还是讲述故事？',
        'tutorial-step2-title': '第2步：制作您的提示',
        'tutorial-step2-desc': '写一个详细的文本描述，包括您想要传达的场景、角色、动作和情感。',
        'tutorial-step3-title': '第3步：选择视频风格',
        'tutorial-step3-desc': '选择与您的品牌和信息匹配的适当视频风格。考虑企业、创意或社交媒体风格。',
        'tutorial-step4-title': '第4步：生成和完善',
        'tutorial-step4-desc': '生成您的视频并查看结果。如需获得最佳效果，可根据需要调整您的提示。'
    }
};

// 提示词数据
const promptsData = {
    'en': [
        'A cyberpunk samurai walking through neon-lit Tokyo streets in heavy rain',
        'Time-lapse of a blooming flower garden transforming through four seasons',
        'Underwater ballet performance with jellyfish and coral reef backdrop',
        'Steampunk airship battle above Victorian London with clockwork mechanisms',
        'Ancient library with floating books and magical golden dust particles',
        'Astronaut discovering a crystal cave on an alien planet with bioluminescent life',
        'Medieval dragon breathing rainbow fire while protecting a fairy tale castle',
        'Coffee shop in space station with Earth view through panoramic windows',
        'Origami crane transforming into real bird and flying through paper landscape',
        'Vintage 1950s diner with robots serving milkshakes to time travelers',
        'Enchanted forest where trees dance and leaves sing in harmony',
        'Miniature world inside a snow globe with tiny people living their lives',
        'Phoenix rising from ashes in slow motion with golden feather details',
        'Underwater city with mermaids swimming between coral skyscrapers',
        'Time portal opening in ancient Egyptian pyramid revealing modern city',
        'Giant mechanical whale swimming through clouds above mountain peaks',
        'Fairy tale cottage made of candy with gingerbread walls and chocolate roof',
        'Holographic concert where digital musicians play for virtual audience',
        'Arctic expedition discovering frozen mammoth with aurora borealis overhead',
        'Floating islands connected by rainbow bridges in pastel sky',
        'Clockwork butterfly garden with mechanical flowers blooming in sequence',
        'Pirate ship sailing through storm of shooting stars in cosmic ocean',
        'Glass greenhouse on Mars growing Earth plants in red soil',
        'Medieval knight riding robotic horse through futuristic battlefield',
        'Underwater tea party with octopus host serving kelp cookies',
        'Crystal cathedral with light beams creating rainbow prisms everywhere',
        'Time-traveling train passing through different historical eras',
        'Bioluminescent mushroom forest with fairy lights and glowing creatures',
        'Floating market in Venice with gondolas selling magical potions',
        'Giant tree house city with rope bridges and wooden elevators'
    ],
    'zh': [
        '赛博朋克武士在霓虹灯闪烁的东京街头雨夜中穿行',
        '花园四季变迁延时摄影，从春花绽放到冬雪覆盖',
        '水下芭蕾表演，舞者与水母共舞在珊瑚礁背景中',
        '蒸汽朋克飞艇在维多利亚时代伦敦上空激战，齿轮机械运转',
        '古老图书馆中书籍悬浮飞舞，金色魔法粒子闪闪发光',
        '宇航员在外星球水晶洞穴中发现生物发光的神秘生命',
        '中世纪巨龙喷射彩虹火焰，守护着童话般的城堡',
        '太空站咖啡厅，透过全景窗户欣赏地球美景',
        '纸折千纸鹤变成真鸟，在纸质风景中自由飞翔',
        '复古50年代餐厅，机器人为时空旅行者调制奶昔',
        '魔法森林中树木翩翩起舞，树叶和谐歌唱',
        '雪花球内的微缩世界，小人们过着精彩的生活',
        '凤凰浴火重生慢镜头，金色羽毛细节纤毫毕现',
        '水下城市中美人鱼在珊瑚摩天楼间自由游弋',
        '古埃及金字塔内时空门户开启，现代都市若隐若现',
        '机械巨鲸在云海中游弋，俯瞰连绵山峰',
        '糖果童话小屋，姜饼墙壁巧克力屋顶甜蜜诱人',
        '全息音乐会，数字音乐家为虚拟观众倾情演出',
        '北极探险队发现冰封猛犸象，极光在头顶绚烂舞动',
        '浮空岛屿由彩虹桥连接，漂浮在粉色天空中',
        '发条蝴蝶花园，机械花朵按序列绽放',
        '海盗船在流星雨中航行，穿越宇宙海洋',
        '火星玻璃温室，在红色土壤中培育地球植物',
        '中世纪骑士骑着机器马，驰骋未来战场',
        '水下茶话会，章鱼主人招待客人品尝海带饼干',
        '水晶大教堂，光束创造出满天彩虹棱镜',
        '时空旅行列车穿越不同历史时代',
        '生物发光蘑菇森林，仙女灯光与发光生物共舞',
        '威尼斯浮动市场，贡多拉船夫售卖神奇魔法药水',
        '巨树屋城市，绳桥相连木质电梯上下穿梭'
    ]
};